
services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data 
    
    command: redis-server --appendonly yes
    
  backend:
    build: .
    container_name: core

    environment:
      - DEBUG=True
      - SECRET_KEY=test
      - CHANNEL_HOST=redis://redis:6379/1
    
    ports:
      - 8000:8000
    
    volumes:
      - ./core:/app

    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - redis
    
volumes:
  redis_data: