# Generated by Django 6.0.4 on 2026-04-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_caht_chat_rename_titile_chat_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sernder',
            new_name='sender',
        ),
    ]
